---
- hosts: localhost
  gather_facts: no
  vars:
   volname: test_data
   vol_id: vol-xxxxxxxx
  tasks:
  - name: Create a Data Volume
    ec2_vol:
     zone: us-east-1a
     region: us-east-1
     name: "{{ volname }}"
     volume_size: 1
     volume_type: gp2
     state: present
    tags: create

  - name: Attach "{{ volname }}" EBS Volume to Instance.
    ec2_vol:
     instance: i-090b77c5dfca2e28d
     name: "{{ volname }}"
     zone: us-east-1a
     region: us-east-1
     state: present
    tags: attach

  - name: Delete a Data Volume
    ec2_vol:
     name: "{{ volname }}"
     #zone: us-east-1a
     id: vol-0813dd7aeaf79a975
     region: us-east-1
     state: absent
    tags: delete
